name: Build PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: API Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PAT }}

      - name: Determine tag
        id: tag
        run: |
          short_sha=$(echo "${{ github.sha }}" | cut -c1-6)
          echo "tag=${short_sha}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
